services:
  backend:
    container_name: teor-izmer-backend
    image: node:18.20.6-alpine3.21
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn && yarn serve-docker"

  db:
    container_name: teor-izmer-db
    image: mysql:8.4.2
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: ./Database/sharedFolder
        target: /sharedFolder
      - db:/var/lib/mysql
      - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'user'
      MYSQL_USER_PASSWORD: 'userpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    networks:
      - app-network

  phpmyadmin:
    container_name: teor-izmer-pma
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "9090:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
